version: "3.7"

services:
  gamekit:
    image: ghcr.io/buttercheetah/gamekit:latest
    restart: unless-stopped
    environment:
      - STEAM_KEY=<changeme>
      - TIMEZONE=UTC
    ports:
      - 9996:5000
  watchtower :
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped